/* The following code was generated by JFlex 1.3.5 on 11/6/24, 7:29 PM */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/6/24, 7:29 PM from the specification file
 * <tt>file:/W:/Eclipse/TranslatorDesign/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\12\1\3\1\2\1\0\1\3\1\1\16\12\4\0\1\3\3\0"+
    "\1\11\1\10\1\15\1\0\1\26\1\27\1\7\1\13\1\35\1\14"+
    "\1\0\1\6\1\4\11\5\1\25\1\34\1\23\1\22\1\24\2\0"+
    "\32\11\1\32\1\0\1\33\1\0\1\11\1\0\1\46\1\50\1\55"+
    "\1\44\1\41\1\37\1\51\1\40\1\36\2\11\1\43\1\11\1\17"+
    "\1\20\1\52\1\11\1\45\1\47\1\21\1\56\1\53\1\42\2\11"+
    "\1\54\1\30\1\16\1\31\1\0\41\12\2\0\4\11\4\0\1\11"+
    "\2\0\1\12\7\0\1\11\4\0\1\11\5\0\27\11\1\0\37\11"+
    "\1\0\u01ca\11\4\0\14\11\16\0\5\11\7\0\1\11\1\0\1\11"+
    "\21\0\160\12\5\11\1\0\2\11\2\0\4\11\1\0\1\11\6\0"+
    "\1\11\1\0\3\11\1\0\1\11\1\0\24\11\1\0\123\11\1\0"+
    "\213\11\1\0\5\12\2\0\246\11\1\0\46\11\2\0\1\11\6\0"+
    "\51\11\6\0\1\11\1\0\55\12\1\0\1\12\1\0\2\12\1\0"+
    "\2\12\1\0\1\12\10\0\33\11\4\0\4\11\15\0\6\12\5\0"+
    "\1\11\4\0\13\12\1\0\1\12\3\0\53\11\37\12\4\0\2\11"+
    "\1\12\143\11\1\0\1\11\10\12\1\0\6\12\2\11\2\12\1\0"+
    "\4\12\2\11\12\12\3\11\2\0\1\11\17\0\1\12\1\11\1\12"+
    "\36\11\33\12\2\0\131\11\13\12\1\11\16\0\12\12\41\11\11\12"+
    "\2\11\4\0\1\11\2\0\1\12\30\11\4\12\1\11\11\12\1\11"+
    "\3\12\1\11\5\12\22\0\31\11\3\12\4\0\13\11\5\0\30\11"+
    "\1\0\6\11\1\0\2\12\6\0\10\12\52\11\72\12\66\11\3\12"+
    "\1\11\22\12\1\11\7\12\12\11\2\12\2\0\12\12\1\0\20\11"+
    "\3\12\1\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0"+
    "\1\11\3\0\4\11\2\0\1\12\1\11\7\12\2\0\2\12\2\0"+
    "\3\12\1\11\10\0\1\12\4\0\2\11\1\0\3\11\2\12\2\0"+
    "\12\12\4\11\7\0\2\11\1\0\1\12\2\0\3\12\1\0\6\11"+
    "\4\0\2\11\2\0\26\11\1\0\7\11\1\0\2\11\1\0\2\11"+
    "\1\0\2\11\2\0\1\12\1\0\5\12\4\0\2\12\2\0\3\12"+
    "\3\0\1\12\7\0\4\11\1\0\1\11\7\0\14\12\3\11\1\12"+
    "\13\0\3\12\1\0\11\11\1\0\3\11\1\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\5\11\2\0\1\12\1\11\10\12\1\0\3\12"+
    "\1\0\3\12\2\0\1\11\17\0\2\11\2\12\2\0\12\12\1\0"+
    "\1\11\7\0\1\11\6\12\1\0\3\12\1\0\10\11\2\0\2\11"+
    "\2\0\26\11\1\0\7\11\1\0\2\11\1\0\5\11\2\0\1\12"+
    "\1\11\7\12\2\0\2\12\2\0\3\12\7\0\3\12\4\0\2\11"+
    "\1\0\3\11\2\12\2\0\12\12\1\0\1\11\20\0\1\12\1\11"+
    "\1\0\6\11\3\0\3\11\1\0\4\11\3\0\2\11\1\0\1\11"+
    "\1\0\2\11\3\0\2\11\3\0\3\11\3\0\14\11\4\0\5\12"+
    "\3\0\3\12\1\0\4\12\2\0\1\11\6\0\1\12\16\0\12\12"+
    "\11\0\1\11\6\0\5\12\10\11\1\0\3\11\1\0\27\11\1\0"+
    "\20\11\2\0\1\12\1\11\7\12\1\0\3\12\1\0\4\12\7\0"+
    "\2\12\1\0\3\11\2\0\1\11\2\0\2\11\2\12\2\0\12\12"+
    "\20\0\1\11\3\12\1\0\10\11\1\0\3\11\1\0\27\11\1\0"+
    "\12\11\1\0\5\11\2\0\1\12\1\11\7\12\1\0\3\12\1\0"+
    "\4\12\7\0\2\12\6\0\2\11\1\0\2\11\2\12\2\0\12\12"+
    "\1\0\2\11\1\12\14\0\4\12\11\11\1\0\3\11\1\0\51\11"+
    "\2\12\1\11\7\12\1\0\3\12\1\0\4\12\1\11\5\0\3\11"+
    "\1\12\7\0\3\11\2\12\2\0\12\12\12\0\6\11\1\0\3\12"+
    "\1\0\22\11\3\0\30\11\1\0\11\11\1\0\1\11\2\0\7\11"+
    "\3\0\1\12\4\0\6\12\1\0\1\12\1\0\10\12\6\0\12\12"+
    "\2\0\2\12\15\0\60\11\1\12\2\11\7\12\4\0\10\11\10\12"+
    "\1\0\12\12\47\0\2\11\1\0\1\11\1\0\5\11\1\0\30\11"+
    "\1\0\1\11\1\0\12\11\1\12\2\11\11\12\1\11\2\0\5\11"+
    "\1\0\1\11\1\0\7\12\1\0\12\12\2\0\4\11\40\0\1\11"+
    "\27\0\2\12\6\0\12\12\13\0\1\12\1\0\1\12\1\0\1\12"+
    "\4\0\2\12\10\11\1\0\44\11\4\0\24\12\1\0\2\12\5\11"+
    "\13\12\1\0\44\12\11\0\1\12\71\0\53\11\24\12\1\11\12\12"+
    "\6\0\6\11\4\12\4\11\3\12\1\11\3\12\2\11\7\12\3\11"+
    "\4\12\15\11\14\12\1\11\17\12\2\0\46\11\1\0\1\11\5\0"+
    "\1\11\2\0\53\11\1\0\u014d\11\1\0\4\11\2\0\7\11\1\0"+
    "\1\11\1\0\4\11\2\0\51\11\1\0\4\11\2\0\41\11\1\0"+
    "\4\11\2\0\7\11\1\0\1\11\1\0\4\11\2\0\17\11\1\0"+
    "\71\11\1\0\4\11\2\0\103\11\2\0\3\12\40\0\20\11\20\0"+
    "\126\11\2\0\6\11\3\0\u026c\11\2\0\21\11\1\0\32\11\5\0"+
    "\113\11\3\0\13\11\7\0\22\11\4\12\11\0\23\11\3\12\13\0"+
    "\22\11\2\12\14\0\15\11\1\0\3\11\1\0\2\12\14\0\64\11"+
    "\40\12\3\0\1\11\3\0\2\11\1\12\2\0\12\12\41\0\17\12"+
    "\6\0\131\11\7\0\5\11\2\12\42\11\1\12\1\11\5\0\106\11"+
    "\12\0\37\11\1\0\14\12\4\0\14\12\12\0\12\12\36\11\2\0"+
    "\5\11\13\0\54\11\4\0\32\11\6\0\12\12\46\0\27\11\5\12"+
    "\4\0\65\11\12\12\1\0\35\12\2\0\13\12\6\0\12\12\15\0"+
    "\1\11\10\0\16\12\1\0\20\12\61\0\5\12\57\11\21\12\10\11"+
    "\3\0\12\12\21\0\11\12\14\0\3\12\36\11\15\12\2\11\12\12"+
    "\54\11\16\12\14\0\44\11\24\12\10\0\12\12\3\0\3\11\12\12"+
    "\44\11\2\0\11\11\7\0\53\11\2\0\3\11\20\0\3\12\1\0"+
    "\25\12\4\11\1\12\6\11\1\12\2\11\3\12\1\11\5\0\300\11"+
    "\100\12\u0116\11\2\0\6\11\2\0\46\11\2\0\6\11\2\0\10\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\1\0\37\11\2\0\65\11"+
    "\1\0\7\11\1\0\1\11\3\0\3\11\1\0\7\11\3\0\4\11"+
    "\2\0\6\11\4\0\15\11\5\0\3\11\1\0\7\11\16\0\5\12"+
    "\32\0\5\12\20\0\2\11\23\0\1\11\13\0\5\12\1\0\12\12"+
    "\1\0\1\11\15\0\1\11\20\0\15\11\3\0\41\11\17\0\15\12"+
    "\4\0\1\12\3\0\14\12\21\0\1\11\4\0\1\11\2\0\12\11"+
    "\1\0\1\11\3\0\5\11\6\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\4\11\1\0\13\11\2\0\4\11\5\0\5\11\4\0\1\11"+
    "\21\0\51\11\u0a77\0\345\11\6\0\4\11\3\12\2\11\14\0\46\11"+
    "\1\0\1\11\5\0\1\11\2\0\70\11\7\0\1\11\17\0\1\12"+
    "\27\11\11\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11\1\0"+
    "\7\11\1\0\7\11\1\0\7\11\1\0\7\11\1\0\40\12\57\0"+
    "\1\11\u01d5\0\3\11\31\0\11\11\6\12\1\0\5\11\2\0\5\11"+
    "\4\0\126\11\2\0\2\12\2\0\3\11\1\0\132\11\1\0\4\11"+
    "\5\0\53\11\1\0\136\11\21\0\40\11\60\0\20\11\u0200\0\u19c0\11"+
    "\100\0\u568d\11\103\0\56\11\2\0\u010d\11\3\0\20\11\12\12\2\11"+
    "\24\0\57\11\1\12\4\0\12\12\1\0\37\11\2\12\120\11\2\12"+
    "\45\0\11\11\2\0\147\11\2\0\100\11\5\0\2\11\1\0\1\11"+
    "\1\0\5\11\30\0\20\11\1\12\3\11\1\12\4\11\1\12\27\11"+
    "\5\12\4\0\1\12\13\0\1\11\7\0\64\11\14\0\2\12\62\11"+
    "\22\12\12\0\12\12\6\0\22\12\6\11\3\0\1\11\1\0\2\11"+
    "\13\12\34\11\10\12\2\0\27\11\15\12\14\0\35\11\3\0\4\12"+
    "\57\11\16\12\16\0\1\11\12\12\6\0\5\11\1\12\12\11\12\12"+
    "\5\11\1\0\51\11\16\12\11\0\3\11\1\12\10\11\2\12\2\0"+
    "\12\12\6\0\27\11\3\0\1\11\3\12\62\11\1\12\1\11\3\12"+
    "\2\11\2\12\5\11\2\12\1\11\1\12\1\11\30\0\3\11\2\0"+
    "\13\11\5\12\2\0\3\11\2\12\12\0\6\11\2\0\6\11\2\0"+
    "\6\11\11\0\7\11\1\0\7\11\1\0\53\11\1\0\16\11\6\0"+
    "\163\11\10\12\1\0\2\12\2\0\12\12\6\0\u2ba4\11\14\0\27\11"+
    "\4\0\61\11\u2104\0\u016e\11\2\0\152\11\46\0\7\11\14\0\5\11"+
    "\5\0\1\11\1\12\12\11\1\0\15\11\1\0\5\11\1\0\1\11"+
    "\1\0\2\11\1\0\2\11\1\0\154\11\41\0\u016b\11\22\0\100\11"+
    "\2\0\66\11\50\0\15\11\3\0\20\12\20\0\20\12\3\0\2\11"+
    "\30\0\3\11\31\0\1\11\6\0\5\11\1\0\207\11\2\0\1\12"+
    "\4\0\1\11\13\0\12\12\7\0\32\11\4\0\1\11\1\0\32\11"+
    "\13\0\131\11\3\0\6\11\2\0\6\11\2\0\6\11\2\0\3\11"+
    "\3\0\2\11\3\0\2\11\22\0\3\12\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    47,    94,   141,    94,   188,   235,   282,    94,   329, 
      376,    94,    94,   423,   470,   517,   564,   611,    94,   658, 
      705,    94,    94,    94,    94,    94,    94,    94,    94,   752, 
      799,   846,   893,   940,   987,  1034,  1081,  1128,  1175,  1222, 
     1269,  1316,  1363,   329,  1410,    94,    94,    94,  1457,  1504, 
     1551,    94,    94,    94,  1598,   376,  1645,  1692,  1739,  1786, 
     1833,  1880,   376,  1927,  1974,  2021,  2068,  2115,  2162,  2209, 
     1269,  1316,  2256,   376,  2303,  2350,   376,  2397,  2444,   376, 
      376,  2491,  2538,  2585,  2632,  2679,  2726,  2773,  2820,   376, 
     2867,   376,   376,  2914,  2961,   376,  3008,  3055,   376,   376, 
      376,   376,  3102,  3149,   376,   376,   376,   376,  3196,   376, 
      376,   376
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\3\1\14\1\15\1\16\1\17\1\20\1\13"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\13"+
    "\1\40\1\41\1\13\1\42\1\43\1\13\1\44\1\45"+
    "\1\13\1\46\1\47\1\13\1\50\1\13\57\3\61\0"+
    "\1\5\54\0\2\51\1\0\1\51\2\52\53\51\1\0"+
    "\1\51\2\7\51\51\7\0\1\53\47\0\1\54\1\55"+
    "\1\56\54\54\4\0\2\13\3\0\2\13\4\0\3\13"+
    "\14\0\21\13\15\0\1\57\57\0\1\60\44\0\2\13"+
    "\3\0\2\13\4\0\1\13\1\61\1\13\14\0\21\13"+
    "\4\0\2\13\3\0\2\13\4\0\3\13\14\0\2\13"+
    "\1\62\4\13\1\63\11\13\23\0\1\64\55\0\1\65"+
    "\56\0\1\66\40\0\2\13\3\0\2\13\4\0\1\67"+
    "\2\13\14\0\1\13\1\70\17\13\4\0\2\13\3\0"+
    "\2\13\4\0\3\13\14\0\5\13\1\71\2\13\1\72"+
    "\7\13\1\73\4\0\2\13\3\0\2\13\4\0\1\74"+
    "\2\13\14\0\5\13\1\75\13\13\4\0\2\13\3\0"+
    "\2\13\4\0\3\13\14\0\2\13\1\76\16\13\4\0"+
    "\2\13\3\0\2\13\4\0\1\13\1\77\1\13\14\0"+
    "\21\13\4\0\2\13\3\0\2\13\4\0\3\13\14\0"+
    "\3\13\1\100\15\13\4\0\2\13\3\0\2\13\4\0"+
    "\3\13\14\0\1\101\20\13\4\0\2\13\3\0\2\13"+
    "\4\0\1\13\1\102\1\13\14\0\3\13\1\103\15\13"+
    "\4\0\2\13\3\0\2\13\4\0\3\13\14\0\7\13"+
    "\1\104\11\13\4\0\2\13\3\0\2\13\4\0\3\13"+
    "\14\0\10\13\1\105\10\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\3\13\1\106\15\13\4\0\2\107"+
    "\51\0\2\51\1\0\1\51\2\110\51\51\7\53\1\111"+
    "\47\53\2\0\1\56\60\0\2\13\3\0\2\13\4\0"+
    "\2\13\1\112\14\0\21\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\3\13\1\113\15\13\4\0\2\13"+
    "\3\0\2\13\4\0\3\13\14\0\20\13\1\114\4\0"+
    "\2\13\3\0\2\13\4\0\2\13\1\115\14\0\21\13"+
    "\4\0\2\13\3\0\2\13\4\0\1\13\1\116\1\13"+
    "\14\0\21\13\4\0\2\13\3\0\2\13\4\0\3\13"+
    "\14\0\5\13\1\117\13\13\4\0\2\13\3\0\2\13"+
    "\4\0\1\120\2\13\14\0\21\13\4\0\2\13\3\0"+
    "\2\13\4\0\3\13\14\0\6\13\1\121\12\13\4\0"+
    "\2\13\3\0\2\13\4\0\3\13\14\0\11\13\1\122"+
    "\7\13\4\0\2\13\3\0\2\13\4\0\3\13\14\0"+
    "\1\123\20\13\4\0\2\13\3\0\2\13\4\0\2\13"+
    "\1\124\14\0\10\13\1\125\10\13\4\0\2\13\3\0"+
    "\2\13\4\0\3\13\14\0\16\13\1\126\2\13\4\0"+
    "\2\13\3\0\2\13\4\0\1\13\1\127\1\13\14\0"+
    "\21\13\4\0\2\13\3\0\2\13\4\0\3\13\14\0"+
    "\13\13\1\130\5\13\4\0\2\13\3\0\2\13\4\0"+
    "\3\13\14\0\1\131\20\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\7\13\1\132\11\13\4\0\2\13"+
    "\3\0\2\13\4\0\3\13\14\0\1\133\20\13\6\53"+
    "\1\56\1\111\47\53\4\0\2\13\3\0\2\13\4\0"+
    "\1\134\2\13\14\0\21\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\3\13\1\135\15\13\4\0\2\13"+
    "\3\0\2\13\4\0\1\13\1\136\1\13\14\0\10\13"+
    "\1\137\10\13\4\0\2\13\3\0\2\13\4\0\3\13"+
    "\14\0\11\13\1\114\7\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\3\13\1\140\15\13\4\0\2\13"+
    "\3\0\2\13\4\0\3\13\14\0\5\13\1\141\13\13"+
    "\4\0\2\13\3\0\2\13\4\0\3\13\14\0\20\13"+
    "\1\142\4\0\2\13\3\0\2\13\4\0\3\13\14\0"+
    "\5\13\1\143\1\144\12\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\3\13\1\145\15\13\4\0\2\13"+
    "\3\0\2\13\4\0\3\13\14\0\5\13\1\146\13\13"+
    "\4\0\2\13\3\0\2\13\4\0\3\13\14\0\1\147"+
    "\20\13\4\0\2\13\3\0\2\13\4\0\1\150\2\13"+
    "\14\0\21\13\4\0\2\13\3\0\2\13\4\0\3\13"+
    "\14\0\5\13\1\151\13\13\4\0\2\13\3\0\2\13"+
    "\4\0\3\13\14\0\7\13\1\152\11\13\4\0\2\13"+
    "\3\0\2\13\4\0\2\13\1\153\14\0\21\13\4\0"+
    "\2\13\3\0\2\13\4\0\3\13\14\0\3\13\1\154"+
    "\15\13\4\0\2\13\3\0\2\13\4\0\3\13\14\0"+
    "\7\13\1\155\11\13\4\0\2\13\3\0\2\13\4\0"+
    "\1\156\2\13\14\0\21\13\4\0\2\13\3\0\2\13"+
    "\4\0\2\13\1\157\14\0\21\13\4\0\2\13\3\0"+
    "\2\13\4\0\1\160\2\13\14\0\21\13";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  9,  1,  1,  9,  9,  1,  1,  1, 
     1,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  1,  9,  9,  9, 
     1,  1,  1,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3243];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2274) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 19: 
          {  return symbolFactory.newSymbol("GT", GT);  }
        case 113: break;
        case 18: 
          {  return symbolFactory.newSymbol("LT", LT);  }
        case 114: break;
        case 47: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 115: break;
        case 51: 
          {  return symbolFactory.newSymbol("LE", LE);  }
        case 116: break;
        case 52: 
          {  return symbolFactory.newSymbol("GE", GE);  }
        case 117: break;
        case 55: 
          {  return symbolFactory.newSymbol("IF", IF);  }
        case 118: break;
        case 62: 
          {  return symbolFactory.newSymbol("DO", DO);  }
        case 119: break;
        case 5: 
        case 6: 
          {  return symbolFactory.newSymbol("IVAL", IVAL, Integer.parseInt(yytext()));  }
        case 120: break;
        case 3: 
        case 4: 
          {                                }
        case 121: break;
        case 70: 
        case 71: 
          {  return symbolFactory.newSymbol( "RVAL", RVAL , Double . valueOf ( yytext ()));  }
        case 122: break;
        case 10: 
        case 15: 
        case 16: 
        case 29: 
        case 30: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 48: 
        case 49: 
        case 50: 
        case 54: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 74: 
        case 75: 
        case 77: 
        case 78: 
        case 81: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 87: 
        case 88: 
        case 90: 
        case 93: 
        case 94: 
        case 96: 
        case 97: 
        case 102: 
        case 103: 
        case 108: 
          {  return symbolFactory.newSymbol("ID", ID, yytext());  }
        case 123: break;
        case 110: 
          {  return symbolFactory.newSymbol("PRINT", PRINT);  }
        case 124: break;
        case 109: 
          {  return symbolFactory.newSymbol("BEGIN", BEGIN);  }
        case 125: break;
        case 107: 
          {  return symbolFactory.newSymbol("WHILE", WHILE);  }
        case 126: break;
        case 106: 
          {  return symbolFactory.newSymbol("FLOAT", FLOAT);  }
        case 127: break;
        case 105: 
          {  return symbolFactory.newSymbol("FLOOR", FLOOR);  }
        case 128: break;
        case 25: 
          {  return symbolFactory.newSymbol("SLPAR", SLPAR);  }
        case 129: break;
        case 24: 
          {  return symbolFactory.newSymbol("CRPAR", CRPAR);  }
        case 130: break;
        case 23: 
          {  return symbolFactory.newSymbol("CLPAR", CLPAR);  }
        case 131: break;
        case 20: 
          {  return symbolFactory.newSymbol("COLON", COLON);  }
        case 132: break;
        case 17: 
          {  return symbolFactory.newSymbol("EQUAL", EQUAL);  }
        case 133: break;
        case 26: 
          {  return symbolFactory.newSymbol("SRPAR", SRPAR);  }
        case 134: break;
        case 28: 
          {  return symbolFactory.newSymbol("COMMA", COMMA);  }
        case 135: break;
        case 2: 
        case 9: 
        case 13: 
        case 14: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 136: break;
        case 7: 
          {  return symbolFactory.newSymbol("DIV", DIV);  }
        case 137: break;
        case 8: 
          {  return symbolFactory.newSymbol("MUL", MUL);  }
        case 138: break;
        case 11: 
          {  return symbolFactory.newSymbol("ADD", ADD);  }
        case 139: break;
        case 12: 
          {  return symbolFactory.newSymbol("SUB", SUB);  }
        case 140: break;
        case 46: 
          {  return symbolFactory.newSymbol("AND", AND);  }
        case 141: break;
        case 73: 
          {  return symbolFactory.newSymbol("NOT", NOT);  }
        case 142: break;
        case 76: 
          {  return symbolFactory.newSymbol("INT", INT);  }
        case 143: break;
        case 79: 
          {  return symbolFactory.newSymbol("FUN", FUN);  }
        case 144: break;
        case 80: 
          {  return symbolFactory.newSymbol("END", END);  }
        case 145: break;
        case 89: 
          {  return symbolFactory.newSymbol("VAR", VAR);  }
        case 146: break;
        case 104: 
          {  return symbolFactory.newSymbol("CEIL", CEIL);  }
        case 147: break;
        case 101: 
          {  return symbolFactory.newSymbol("BOOL", BOOL);  }
        case 148: break;
        case 100: 
          {  return symbolFactory.newSymbol("SIZE", SIZE);  }
        case 149: break;
        case 99: 
          {  return symbolFactory.newSymbol("READ", READ);  }
        case 150: break;
        case 98: 
          {  return symbolFactory.newSymbol("REAL", REAL);  }
        case 151: break;
        case 95: 
          {  return symbolFactory.newSymbol("ELSE", ELSE);  }
        case 152: break;
        case 92: 
          {  return symbolFactory.newSymbol("BVAL", BVAL);  }
        case 153: break;
        case 22: 
          {  return symbolFactory.newSymbol("RPAR", RPAR);  }
        case 154: break;
        case 21: 
          {  return symbolFactory.newSymbol("LPAR", LPAR);  }
        case 155: break;
        case 91: 
          {  return symbolFactory.newSymbol("THEN", THEN);  }
        case 156: break;
        case 27: 
          {  return symbolFactory.newSymbol("SEMICOLON", SEMICOLON);  }
        case 157: break;
        case 111: 
          {  return symbolFactory.newSymbol("RETURN", RETURN);  }
        case 158: break;
        case 53: 
          {  return symbolFactory.newSymbol("ASSIGN", ASSIGN);  }
        case 159: break;
        case 44: 
        case 45: 
          {  /*Ignore Comments*/ }
        case 160: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
